### PR TITLE
Added activation steps of Jetbrains for Windows

### PR DESCRIPTION
**Pull request by JusethAg**
I splitted the activation steps of JetBrains for Windows and Mac, because It's a little different the location of folders for both SO. (I added the steps for Windows)

### CODE REVIEW

**Comment by JusethAg** [comment]
In addition to my pull request (I'm newbie), I'd like to say that when I was finding how to apply this theme for IntelliJ IDE on Windows. I found the solution in the instructions of [IntelliJ Colors Solarized repository](https://github.com/jkaving/intellij-colors-solarized).Then, I saw that depending on the version of JetBrains, the PATH could change. Hence I would like to suggest to change the following couple of PATH:
* **%USERPROFILE%\\.IdeaICXX\config** *to* **%USERPROFILE%\\.{JetBrainsVersion}</b>\config** 

* **%USERPROFILE%\\.IdeaICXX\config\colors** *to* **%USERPROFILE%\\.{JetBrainsVersion}\config\colors**

**Comment by zenorocha** [comment]
Thanks a lot for this contribution @JusethAg!

@joaoevangelista, can you review this one?

**Comment by nesl247** [comment]
`IdeaICXX` and `{JetBrainsVersion}` should actually be similar to the way we mention Mac, because it's the same thing. It's the IDE name and version.

**Comment by zenorocha** [comment]
Closing in favor of #41

**Pull request closed without merging**
