### PR TITLE
fix incorrect vim install instructions

### PR DESCRIPTION
**Pull request by dsifford**
See dracula/vim#138

### CODE REVIEW

**Comment by hacknug** [comment]
@dsifford @benknoble not much of a Vim guy so could you folks let me know this is 100% correct so I can merge?

**Comment by benknoble** [comment]
@hacknug we are still waiting for https://github.com/dsifford/dracula.github.io/pull/1 now that we've released version 2.0 of vim theme; we introduced some changes that seem to be breaking for some users, and want to make sure the documentation for the fix is as prevalent as possible.

The above pull request onto the tip of this PR incorporates the new documentation. Once it merges, this PR will be ready.

**Comment by dsifford** [comment]
Didn't see that PR into my fork. Whoops, thanks for the reminder @benknoble

**Comment by hacknug** [comment]
Great! Let me know when/if you need me to merge this 👌

**Comment by benknoble** [comment]
@dsifford looks ready to me? Thanks @hacknug for your help!

**Comment by dsifford** [comment]
LGTM

**Comment by hacknug** [comment]
Thank you!

**Pull request merged**
